[package]
name = "FerrousLearn"
version = "0.1.6"
authors = ["John Denton"]
edition = "2021"
description = "dependency-free, from-scratch machine learning"
readme = "README.md"
repository = "https://github.com/lm-bds/FerrousLearn.git"
license = "MIT OR Apache-2.0"
keywords = ["machine-learning"]
categories = ["machine learning"]
include = ["/src"]
