[package]
name = "ferrouslearn"
version = "0.1.8"
authors = ["lm-bds contributors"]
edition = "2021"
description = "dependency-free, from-scratch machine learning"
readme = "README.md"
repository = "https://github.com/lm-bds/FerrousLearn.git"
license = "MIT"
keywords = ["machine-learning"]
categories = ["artificial-intelligence"]

[lib]
path = "src/lib.rs"

[dependencies]

[dev-dependencies]
criterion = "0.5"
proptest = "1"

[[bench]]
name = "kmeans"
harness = false

[[bench]]
name = "pca"
harness = false

[[bench]]
name = "regression"
harness = false
