[advisories]
version = 2
yanked = "deny"
ignore = []

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"
deny = []
skip = []
skip-tree = []

[licenses]
version = 2
allow = ["MIT"]
confidence-threshold = 0.8

[sources]
unknown-registry = "deny"
unknown-git = "deny"
